# Generated by Django 6.0.5 on 2026-06-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='cgst_rate',
            field=models.DecimalField(decimal_places=2, default=9, max_digits=5),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=5),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='sgst_rate',
            field=models.DecimalField(decimal_places=2, default=9, max_digits=5),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='taxable_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='unit',
            field=models.CharField(default='Pcs.', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
