# Generated by Django 6.0.5 on 2026-06-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gstin',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
