# Generated by Django 6.0.5 on 2026-06-01 06:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['shortcut', 'name']},
        ),
        migrations.AddField(
            model_name='product',
            name='shortcut',
            field=models.CharField(blank=True, help_text='Short code for quick selection, e.g. WD, HOST', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('shortcut__gt', '')), fields=('user', 'shortcut'), name='unique_product_shortcut_per_user'),
        ),
    ]
