# Generated by Django 6.0.5 on 2026-06-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_product_shortcut_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['shortcut', 'name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Product master'},
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Optional notes about the product (not printed on invoice by default).', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=18, help_text='Total GST percentage on this product (typically 5, 12, 18, or 28).', max_digits=5, verbose_name='GST rate (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, help_text='Harmonized System of Nomenclature (goods) or Service Accounting Code (services) — GST classification code, usually 4–8 digits (e.g. 847160 for computer mouse).', max_length=20, verbose_name='HSN / SAC code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive products are hidden from new invoice item selection.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Display name shown on tax invoice line items.', max_length=200, verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price per unit before GST is added.', max_digits=12, verbose_name='Unit price (excl. GST)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shortcut',
            field=models.CharField(blank=True, help_text='Short code for quick invoice entry (e.g. WD for wireless mouse, HOST for hosting).', max_length=20, verbose_name='Shortcut code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit — your unique internal product/inventory code (e.g. MOU-DEL-001, LAP-HP-15S). Optional; different from HSN or shortcut.', max_length=50, verbose_name='SKU (Stock Keeping Unit)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default='pcs', help_text='How quantity is counted on invoice (e.g. pcs, kg, box, hr).', max_length=20, verbose_name='Unit of measure'),
        ),
    ]
