# Generated by Django 6.0.5 on 2026-06-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_field_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=18, help_text='Total GST percentage on this product (typically 5, 12, 18, or 28).', max_digits=5, verbose_name='GST %'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, help_text='HSN = Harmonized System of Nomenclature (goods). SAC = Service Accounting Code (services). GST code, usually 4–8 digits only (e.g. 847160). Do not type "HSN" in this field.', max_length=20, verbose_name='HSN/SAC'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Display name shown on tax invoice line items.', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Unit price excluding GST (₹). Stock Keeping Unit (SKU) is separate from this amount.', max_digits=12, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shortcut',
            field=models.CharField(blank=True, help_text='Short code for quick invoice entry (e.g. WD for wireless mouse, HOST for hosting).', max_length=20, verbose_name='Shortcut'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='SKU = Stock Keeping Unit — your unique internal product/inventory code (e.g. MOU-DEL-001, LAP-HP-15S). Optional; different from HSN or shortcut.', max_length=50, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default='pcs', help_text='How quantity is counted on invoice (e.g. pcs, kg, box, hr).', max_length=20, verbose_name='Unit'),
        ),
    ]
